/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ConsumerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IotServer": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "MockIotSite": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "RT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "mockIotStream": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
  }
}
