/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "IotServer": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "Public": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "RT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
