/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst';
export {};
declare module 'sst' {
	export interface Resource {
		MockIotSite: {
			type: 'sst.aws.SvelteKit';
			url: string;
		};
		MyApiFunction: {
			name: string;
			type: 'sst.aws.Function';
			url: string;
		};
		MyAppBucket: {
			name: string;
			type: 'sst.aws.Bucket';
		};
		MyRouter: {
			type: 'sst.aws.Router';
			url: string;
		};
		mockIotStream: {
			name: string;
			type: 'sst.aws.KinesisStream';
		};
	}
}
